export const INDEX_INFO = {
  VCI: {
    formula: 'VCI = (NDVIi - NDVImin) / (NDVImax - NDVImin) × 100',
    description: 'Pixel-based index to identify drought condition irrespective of ecological region. Value 0 = extreme stress, 100 = healthy vegetation.',
    source: 'MODIS MOD13Q1 (250m, 16-day)',
    reference: 'Kogan F.N. 1995. Advances in Space Research, 15(11): 91-100.',
  },
  TCI: {
    formula: 'TCI = (LSTmax - LSTi) / (LSTmax - LSTmin) × 100',
    description: 'Measures thermal stress on vegetation. Value 0 = extreme heat stress, 100 = no stress.',
    source: 'MODIS MOD11A1 (1km, daily)',
    reference: 'Kogan F.N. 1995. Advances in Space Research, 15(11): 91-100.',
  },
  VHI: {
    formula: 'VHI = α × VCI + (1-α) × TCI',
    description: 'Combines vegetation and temperature condition. Default α=0.5 equal weighting.',
    source: 'MODIS NDVI + LST',
    reference: 'Kogan F.N. 1997. BAMS, 78(4): 621-636.',
  },
  mTVDI: {
    formula: 'mTVDI = (Ts - Tsmin) / (Tsmax - Tsmin)',
    description: 'Modified temperature-vegetation dryness index. Range 0-1, higher = drier. More sensitive than VHI in arid zones.',
    source: 'MODIS LST + NDVI',
    reference: 'Sandholt et al. 2002. Remote Sensing of Environment.',
  },
  SMI: {
    formula: 'SMI = (SM - SMmin) / (SMmax - SMmin)',
    description: 'Normalized soil moisture index. Range 0-1, values near 0 indicate extreme drought.',
    source: 'NASA SMAP SPL4SMGP (9km)',
    reference: 'Hunt et al. 2009. Remote Sensing of Environment.',
  },
  SMCI_SMAP: {
    formula: 'SMCI = (SM - SMmin) / (SMmax - SMmin) × 100',
    description: 'Soil moisture condition index from SMAP. Available from 2015.',
    source: 'NASA SMAP (9km, daily)',
    reference: 'Kogan F.N. 1995.',
  },
  SMCI_FLDAS: {
    formula: 'SMCI = (SM - SMmin) / (SMmax - SMmin) × 100',
    description: 'Soil moisture condition index from FLDAS. Longer record than SMAP, available from 1982.',
    source: 'NASA FLDAS NOAH (0.1°, monthly)',
    reference: 'McNally et al. 2017. Scientific Data.',
  },
  SPI: {
    formula: 'SPI = (P - μ) / σ',
    description: 'WMO standard drought index. Negative values indicate drought. Multi-timescale: 1,3,6,12 months.',
    source: 'CHIRPS (0.05°, pentad)',
    reference: 'McKee et al. 1993. 8th Conference on Applied Climatology.',
  },
  SPEI: {
    formula: 'SPEI = standardized(P - PET)',
    description: 'Like SPI but accounts for evapotranspiration. Better captures temperature-driven drought under climate change.',
    source: 'CSIC SPEI Global v2.10',
    reference: 'Vicente-Serrano et al. 2010. Journal of Climate, 23(7).',
  },
  PDSI: {
    formula: 'PDSI = 0.897 × PDSI(prev) + (Z/3)',
    description: 'Classic drought index accounting for water supply and demand. Range typically -5 to +5.',
    source: 'TerraClimate (~4km, monthly)',
    reference: 'Palmer W.C. 1965. US Weather Bureau Research Paper 45.',
  },
  RDI: {
    formula: 'RDI = standardized(ΣP / ΣPET)',
    description: 'Ratio-based index well suited for arid climates like Balochistan.',
    source: 'ERA5-Land (0.1°, monthly)',
    reference: 'Tsakiris & Vangelis 2005. European Water, 9(10).',
  },
  DRYSPELL: {
    formula: 'DrySpell = count(days where P < threshold)',
    description: 'Counts consecutive or total dry days in a period. Operationally useful for farmers.',
    source: 'CHIRPS Daily (0.05°)',
    reference: 'WMO Guidelines on Drought Indices, 2012.',
  },
  TWSA: {
    formula: 'TWSA = TWS - TWSbaseline',
    description: "Captures total water storage changes including groundwater. Pakistan's groundwater depletion is clearly visible. Note: coarse resolution (~300km), best for province-level.",
    source: 'NASA GRACE/GRACE-FO (monthly)',
    reference: 'Tapley et al. 2004. Science, 305(5683).',
  },
  NDWI: {
    formula: 'NDWI = (Green - NIR) / (Green + NIR)',
    description: 'Surface water stress index. Positive values indicate water presence.',
    source: 'MODIS MOD09GA (500m, daily)',
    reference: 'Gao B.C. 1996. Remote Sensing of Environment, 58(3).',
  },
  SWA: {
    formula: 'SWA = Water_extent(current) - Water_extent(baseline)',
    description: 'Monitors changes in rivers, lakes, and reservoirs relative to long-term baseline.',
    source: 'JRC Global Surface Water (Landsat, 30m)',
    reference: 'Pekel et al. 2016. Nature, 540(7633).',
  },
  NDVI_ANOMALY: {
    formula: 'NDVI_Anomaly = NDVI(current) - NDVI(baseline_mean)',
    description: 'Departure from long-term mean vegetation greenness. Direct crop stress signal.',
    source: 'MODIS MOD13Q1 (250m, 16-day)',
    reference: 'Tucker C.J. 1979. Remote Sensing of Environment, 8(2).',
  },
  NPP_ANOMALY: {
    formula: 'NPP_Anomaly = NPP(current) - NPP(baseline_mean)',
    description: 'Net Primary Productivity departure from baseline. Measures actual carbon fixation loss — stronger drought signal than NDVI alone.',
    source: 'MODIS MOD17A3HGF (500m, annual)',
    reference: 'Running et al. 2004. BioScience, 54(6).',
  },
  LST_ANOMALY: {
    formula: 'LST_Anomaly = LST(current) - LST(baseline_mean)',
    description: 'Land surface temperature departure from baseline. Captures compound heat-drought events.',
    source: 'MODIS MOD11A1 (1km, daily)',
    reference: 'Wan Z. 2008. International Journal of Remote Sensing, 29(17).',
  },
}
